/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    DetalhePokemon: typeof import('./src/components/DetalhePokemon.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    GlobalSnackbar: typeof import('./src/@core/components/GlobalSnackbar.vue')['default']
    HeaderNav: typeof import('./src/components/HeaderNav.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    NotificationBar: typeof import('./src/components/NotificationBar.vue')['default']
    PokemonAbilities: typeof import('./src/components/PokemonAbilities.vue')['default']
    PokemonDetail: typeof import('./src/components/PokemonDetail.vue')['default']
    PokemonImages: typeof import('./src/components/PokemonImages.vue')['default']
    PokemonMoves: typeof import('./src/components/PokemonMoves.vue')['default']
    PokemonStats: typeof import('./src/components/PokemonStats.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    UpgradeToPro: typeof import('./src/components/UpgradeToPro.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
  }
}
